name: SonarQube Scan
on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  next:
    runs-on: github-ubuntu-latest-s
    permissions:
      id-token: write
      pull-requests: read
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - id: secrets
        uses: SonarSource/vault-action-wrapper@320bd31b03e5dacaac6be51bbbb15adf7caccc32 # 3.1.0
        with:
          secrets: |
            development/kv/data/next token | sq_next_token;
            development/kv/data/next url | sq_next_url;
      - name: SonarQube Next Scan
        uses: sonarsource/sonarqube-scan-action@22918119ff8e1ca75a623e15c8296b6ea4fbe28f # v8.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ fromJSON(steps.secrets.outputs.vault).sq_next_token }}
          SONAR_HOST_URL: ${{ fromJSON(steps.secrets.outputs.vault).sq_next_url }}
